[package]
name = "vault2env"
version = "0.1.0"
edition = "2018"

[dependencies]
ureq = { version = "*", features = ["json", "charset"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
